### PR TITLE
[VR-11871] Fix filter ER by hyperparameter predicates

### PR DESCRIPTION
**Pull request by anandjakhaniya**
Jira Ticket: https://vertaai.atlassian.net/browse/VR-11871

### CODE REVIEW

**Review by conradoverta — COMMENTED** [review]
I don't follow what was the issue here and the ticket is empty. Could you provide a description?

**Comment by anandjakhaniya** [comment]
> I don't follow what was the issue here and the ticket is empty. Could you provide a description?

there was an issue while sending empty keys while deleting hyperparameters, metrics etc. and we have implemented Optional there and implemented `Optional.isPresent()` but due to empty list it was giving a true but actual it has empty list so we should have to add empty check for that optional value which i have added now.

**Comment by conradoverta** [comment]
> > I don't follow what was the issue here and the ticket is empty. Could you provide a description?
> 
> there was an issue while sending empty keys while deleting hyperparameters, metrics etc. and we have implemented Optional there and implemented `Optional.isPresent()` but due to empty list it was giving a true but actual it has empty list so we should have to add empty check for that optional value which i have added now.

I think you're taking about the wrong ticket, as this is a filtering one, not a deletion one.

**Comment by anandjakhaniya** [comment]
> > > I don't follow what was the issue here and the ticket is empty. Could you provide a description?
> > 
> > 
> > there was an issue while sending empty keys while deleting hyperparameters, metrics etc. and we have implemented Optional there and implemented `Optional.isPresent()` but due to empty list it was giving a true but actual it has empty list so we should have to add empty check for that optional value which i have added now.
> 
> I think you're taking about the wrong ticket, as this is a filtering one, not a deletion one.

Ohh Ok, I am sorry. it's my bad. So here in database we have store value as a string using `ModelDBUtils.getStringFromProtoObject(value)` while inserting so in database it will keep data with `""` so without `ModelDBUtils.getStringFromProtoObject(value)` , all match are failed so fix logic to used `ModelDBUtils.getStringFromProtoObject(value)` for given predicate value

**Review by conradoverta — APPROVED** [review]

**Pull request merged**
