### PR TITLE
tests: Add action type & data type tests

### PR DESCRIPTION
**Pull request by liuverta**
## Impact and Context

Add tests for client and CLI registry action types and data types.

These require some of my suggested changes in #3079.

## Risks and Area of Effect

—

## Testing

Ensure you have `pytest` installed

```sh
python -m pip install pytest
```

then go to the tests directory

```sh
cd modeldb/client/verta/tests
```

and run tests

```sh
python -m pytest -k "TestActionTypes or TestDataTypes" -vvra
```

Our goal is to see `0 failed`, but currently there is a registry bug on `get()`.

## How to Revert

Revert this PR.

### CODE REVIEW

**Comment by marcelo-verta-ai** [comment]
When I tried to run I have this result

```
marcelo@marcelo-Vostro-5402:/opt/repositorio-git/verta/modeldb/client/verta/tests$ pytest-3 -k "TestActionTypes or TestDataTypes" -vvra
ImportError while loading conftest '/opt/repositorio-git/verta/modeldb/client/verta/tests/conftest.py'.
conftest.py:19: in <module>
    import verta
../verta/__init__.py:5: in <module>
    from .client import Client
../verta/client.py:37: in <module>
    from .registry.entities import (
../verta/registry/entities/__init__.py:6: in <module>
    from ._model import RegisteredModel
../verta/registry/entities/_model.py:16: in <module>
    from .. import action_type as action_type_module
../verta/registry/action_type/__init__.py:14: in <module>
    from ._unknown import Unknown
E   ImportError: cannot import name 'Unknown' from 'verta.registry.action_type._unknown' (/opt/repositorio-git/verta/modeldb/client/verta/verta/registry/action_type/_unknown.py) 
```

After that, I made modifications on __init__.py (action and data type)

```
from ._data_type import _DataType
from ._other import Other
from ._audio import Audio
from ._image import Image
from ._tabular import Tabular
from ._text import Text
from ._video import Video
from ._unknown import _Unknown

documentation.reassign_module(
    [
        Other,
        Audio,
        Image,
        Tabular,
        Text,
        Video,
        _Unknown,
    ],
    module_name=__name__,
)

other = Other()
audio = Audio()
image = Image()
tabular = Tabular()
text = Text()
video = Video()
unknown = _Unknown()
```

test result

```
[TEST LOG] test teardown completed 2022-08-17 19:00:39.683551 UTC
================================================================================ short test summary info =================================================================================
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/test_backend.py:9: reduce DB pressure to establish test baseline
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/test_data_types.py:12: scipy is not installed
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/test_datasets.py:4: outdated tests for legacy API
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/modelapi_hypothesis/test_modelapi.py:8: could not import 'pandas': No module named 'pandas'
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/modelapi_hypothesis/test_value_generator.py:9: could not import 'pandas': No module named 'pandas'
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/models/standard_models.py:101: could not import 'tensorflow.keras': No module named 'tensorflow'
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/test_cli/test_repository.py:11: repository sub-CLI has been disabled
FAILED registry/test_model.py::TestActionTypes::test_creation[Classification] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_creation[Clustering] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_creation[Detection] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_creation[Other] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_creation[Regression] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_creation[Transcription] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_creation[Translation] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_creation[_Unknown] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_set[Classification] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_set[Clustering] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_set[Detection] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_set[Other] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_set[Regression] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_set[Transcription] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_set[Translation] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestActionTypes::test_set[_Unknown] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestDataTypes::test_creation[Audio] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestDataTypes::test_creation[Image] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestDataTypes::test_creation[Other] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestDataTypes::test_creation[Tabular] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestDataTypes::test_creation[Text] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestDataTypes::test_creation[Video] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestDataTypes::test_creation[_Unknown] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestDataTypes::test_set[Audio] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestDataTypes::test_set[Image] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestDataTypes::test_set[Other] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestDataTypes::test_set[Tabular] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestDataTypes::test_set[Text] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestDataTypes::test_set[Video] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED registry/test_model.py::TestDataTypes::test_set[_Unknown] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestActionTypes::test_creation[Classification] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestActionTypes::test_creation[Clustering] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestActionTypes::test_creation[Detection] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestActionTypes::test_creation[Other] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestActionTypes::test_creation[Regression] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestActionTypes::test_creation[Transcription] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestActionTypes::test_creation[Translation] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestActionTypes::test_creation[_Unknown] - AttributeError: module 'verta.registry.action_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestDataTypes::test_creation[Audio] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestDataTypes::test_creation[Image] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestDataTypes::test_creation[Other] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestDataTypes::test_creation[Tabular] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestDataTypes::test_creation[Text] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestDataTypes::test_creation[Video] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
FAILED test_cli/test_registry.py::TestDataTypes::test_creation[_Unknown] - AttributeError: module 'verta.registry.data_type' has no attribute 'Unknown'
================================================================= 45 failed, 7 skipped, 1155 deselected in 89.91 seconds =================================================================
marcelo@marcelo-Vostro-5402:/opt/repositorio-git/verta/modeldb/client/verta/tests$

**Comment by marcelo-verta-ai** [comment]
I ran this test:

```
client = Client("https://dev.verta.ai/", email="[matheus@verta.ai](mailto:matheus@verta.ai)", dev_key="f12535f7-7de1-436e-a3b6-5528694b489b")
registered_model = client.create_registered_model(
    name="model catalog test action class Classification and data class Image",
    labels=["test-purpose", "Novatics"],
    action_type=action_type.Classification(),
    data_type=data_type.Image()
)
```

the result was:

```
connection successfully established
created new RegisteredModel: model catalog test action class Classification and data class Image in workspace: Catalog-testing
name: model catalog test action class Classification and data class Image
url: https://dev.verta.ai/Catalog-testing/registry/4719
time created: 2022-08-17 15:24:38.886000
time updated: 2022-08-17 15:24:38.886000
description:
labels: ['Novatics', 'test-purpose']
id: 4719
```

**Comment by liuverta** [comment]
@marcelo-verta-ai Yes, this PR needs some changes to work, especially as #3079 is being updated too. Would you be willing to help fix this PR and add commits?

**Comment by marcelo-verta-ai** [comment]
> @marcelo-verta-ai Yes, this PR needs some changes to work, especially as #3079 is being updated too. Would you be willing to help fix this PR and add commits?

for sure !!! Can I do this in my PR ? because I merged this one

**Comment by liuverta** [comment]
Oh! Yes, please feel free to add the fixes to #3079. I'll close since PR since I see you've added the commits to your branch.

**Pull request closed without merging**
