### PR TITLE
VR-2639: Use pagination for Dataset RPCs

### PR DESCRIPTION
**Pull request by convoliution**
Copies (literally) the logic from #72. Can be cleaned up later, I'm sure.

For personal reference:
`findDatasets` tested using
```bash
pytest test_datasets.py::TestClientDatasetFunctions::test_find_datasets_client_api
```

`getAllDatasetVersionsByDatasetId` tested using
```bash
pytest test_datasets.py::TestClientDatasetVersionFunctions
```

### CODE REVIEW

**Comment by convoliution** [comment]
> > Copies (literally) the logic from #72. Can be cleaned up later, I'm sure.
> 
> I see no reason to do this copy and push cleaning for later. I see about 2 lines difference between the two versions.

- They use different endpoints. If I combine these classes, I'll need to add this as a parameter.
- One returns `Dataset`s, the other returns `DatasetVersion`s. If I combine these classes, I'll need to add this as a parameter to know what object to return, and hard-code an additional check because the response JSON will either have `'datasets'` or `'dataset_versions'`.
- One makes a POST request, the other makes a GET request. If I combine these classes, I'll need to add this as a parameter to know what request to make, and hard-code an additional check because a POST request requires a `json` kwarg, and a GET request involves a `params` arg (due in part to `requests`'s API).

So combining the two means the constructor will take six parameters in total, and there will be two additional checks looking for `Dataset` vs `DatasetVersion`, and POST vs GET leading to at least 5 additional lines of code, and that's only the things I've thought of! Felt like over-engineering to me.

**Comment by conradoverta** [comment]
Coding is not hard-coding. Don't confuse the two. Adding conditionals to handle multiple paths is the reverse of hard-coding. Over-engineering means it's more complex than necessary. The amount of copy and paste through the client has caused issues before, so I would argue that avoiding copy and paste is not adding unnecessary complexity.

**Comment by convoliution** [comment]
> …I would argue that avoiding copy and paste is not adding unnecessary complexity.

I see, got it.

**Comment by convoliution** [comment]
The iterable classes have been combined, with checks e.g.
```python
if self._element_cls is Dataset
```
to interpret the back end response, and yield the correct elements.

**Comment by convoliution** [comment]
`LazyList` is now an abstract class that is subclassed by `DatasetLazyList`, `DatasetVersionLazyList`, and `ExperimentRuns`.

Passes tests:
```
pytest test_datasets.py::TestClientDatasetFunctions::test_find_datasets_client_api test_datasets.py::TestClientDatasetVersionFunctions::test_get_versions test_query.py test_entities.py::TestExperimentRuns
```

**Pull request merged**
