### PR TITLE
[MRG] Roger tangos/python3

### PR DESCRIPTION
**Pull request by RogerTangos**
* Make imports Python3 friendly
* Add a few python3-isms
* Reimplement/Refactor how ModelDB does `Syncer` Singletons
  * don't pass args to `object.__new__`. Use a `__metaclass__` instead
* Making the singletons python3 friendly

### CODE REVIEW

**Comment by RogerTangos** [comment]
Pushed. I could do some more import cleanup if we think it’s worth it. The issue is that even if all of the tests pass, it’s still likely to break any user workflows. (ModelDbSyncer is importing * from a bunch of places, and who knows what’s being used where…)

**Comment by RogerTangos** [comment]
Hey @mpvartak - The python tests were passing locally on my machine, but no longer are. I think it's due to an update from one of the requirements. Do you have a clue which one it would be? LMK, and then I'll freeze it at a previous version

```
======================================================================
ERROR: test_old_dataframe (testRandomSplitEvent.TestRandomSplitEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arcarter/code/modeldb/client/python/modeldb/tests/sklearn/testRandomSplitEvent.py", line 37, in setUp
    X, y, train_size=0.7))
  File "/Users/arcarter/code/modeldb/client/python/modeldb/sklearn_native/ModelDbSyncer.py", line 258, in train_test_split_fn
    result = split_dfs[:len(split_dfs) / 2]
TypeError: slice indices must be integers or None or have an __index__ method

======================================================================
ERROR: test_random_split_event (testRandomSplitEvent.TestRandomSplitEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arcarter/code/modeldb/client/python/modeldb/tests/sklearn/testRandomSplitEvent.py", line 37, in setUp
    X, y, train_size=0.7))
  File "/Users/arcarter/code/modeldb/client/python/modeldb/sklearn_native/ModelDbSyncer.py", line 258, in train_test_split_fn
    result = split_dfs[:len(split_dfs) / 2]
TypeError: slice indices must be integers or None or have an __index__ method

======================================================================
ERROR: test_split_dataframes (testRandomSplitEvent.TestRandomSplitEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arcarter/code/modeldb/client/python/modeldb/tests/sklearn/testRandomSplitEvent.py", line 37, in setUp
    X, y, train_size=0.7))
  File "/Users/arcarter/code/modeldb/client/python/modeldb/sklearn_native/ModelDbSyncer.py", line 258, in train_test_split_fn
    result = split_dfs[:len(split_dfs) / 2]
TypeError: slice indices must be integers or None or have an __index__ method

======================================================================
FAIL: test_transformer_spec (testFitEvent.TestFitEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arcarter/code/modeldb/client/python/modeldb/tests/sklearn/testFitEvent.py", line 73, in test_transformer_spec
    utils.is_equal_transformer_spec(spec, expected_spec, self)
  File "/Users/arcarter/code/modeldb/client/python/modeldb/tests/utils.py", line 157, in is_equal_transformer_spec
    spec2.hyperparameters[i].name)
AssertionError: 'n_jobs' != 'copy_X'
- n_jobs
+ copy_X


======================================================================
FAIL: test_overall_pipeline_fit_event (testPipelineEvent.TestPipelineEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arcarter/code/modeldb/client/python/modeldb/tests/sklearn/testPipelineEvent.py", line 107, in test_overall_pipeline_fit_event
    utils.is_equal_transformer_spec(spec, expected_spec, self)
  File "/Users/arcarter/code/modeldb/client/python/modeldb/tests/utils.py", line 157, in is_equal_transformer_spec
    spec2.hyperparameters[i].name)
AssertionError: 'pca__whiten' != 'logistic__n_jobs'
- pca__whiten
+ logistic__n_jobs


======================================================================
FAIL: test_pipeline_second_fit_stage (testPipelineEvent.TestPipelineEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arcarter/code/modeldb/client/python/modeldb/tests/sklearn/testPipelineEvent.py", line 188, in test_pipeline_second_fit_stage
    utils.is_equal_transformer_spec(spec, expected_spec, self)
  File "/Users/arcarter/code/modeldb/client/python/modeldb/tests/utils.py", line 157, in is_equal_transformer_spec
    spec2.hyperparameters[i].name)
AssertionError: 'n_jobs' != 'copy_X'
- n_jobs
+ copy_X
```

**Comment by RogerTangos** [comment]
Travis is continuing to choke on the PR. It's unclear why. One of the failures was with `TestPipelineEvent`, which almost makes sense. The other errors have all been with `sudo make thrift`, which is code that hasn't changed in a while, is identical to that on the branch, and passes on the branch.

**Comment by eyadsibai** [comment]
It seems it's passing now @RogerTangos

**Comment by gte620v** [comment]
Thanks for putting together a py3 version!

A couple notes I observed from trying to get this to work:

I think you need to add 
```
if sys.version_info <= (3, 0):
    import ModelDbSyncer
else:
    from . import ModelDbSyncer
```

to `SyncableMetrics.py` and `SyncableRandomMetric.py` too.

Also, with the addition of the `future` package, you need to add that dependency to `setup.py`.

**Comment by RogerTangos** [comment]
@eyadsibai ... Great! And I still have no idea why.

@justinanderson - with @gte620v 's changes, is this something you'd like to merge?

**Comment by justinanderson** [comment]
I'm not 100%, but I think I've resolved all of the remaining Python 2/3 issues.

If anyone wants to test this without checking out the code, I've uploaded a test distribution to PyPi. You can install it with:
```
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple modeldb
```

**Comment by arsenyinfo** [comment]
Hi @justinanderson, are there any plans to merge this PR and make the updated package available via PyPi? It's working nice, but i'm sad i can't install modeldb using `pip install -r requirements.txt`.

**Comment by justinanderson** [comment]
I'll leave merging up to @mpvartak. It sounds like this branch works well enough for people.

**Pull request merged**
