### PR TITLE
VR-7716 unable to search runs by tags

### PR DESCRIPTION
**Pull request by nhatsmrt**
This is all it takes, apparently 🤷 Lmk if I missed sth.

### CODE REVIEW

**Review by convoliution — CHANGES_REQUESTED** [review]
It's been a while so I don't remember, myself:
Looks like the syntax being used here is `tags ~= some-tag`; does `==` work?
Either way, let's also add this to the `Examples` section in the docstring

**Comment by convoliution** [comment]
@conradoverta Should this also be enabled for Projects & Experiments (if it's not, already)?

**Comment by nhatsmrt** [comment]
@convoliution `~=` is contains (according to LazyList's implementation), so it makes more sense for me, but I just double checked and `==` works too 🤷. Lmk which do you prefer.

**Comment by nhatsmrt** [comment]
@convoliution Looks like searching by tags is already allowed in [projects](https://github.com/VertaAI/modeldb/blob/master/client/verta/verta/_tracking/projects.py#L24) and [experiments](https://github.com/VertaAI/modeldb/blob/master/client/verta/verta/_tracking/experiments.py#L24). I think we just missed this one key in runs' implementation :P

**Review by convoliution — APPROVED** [review]
>Looks like searching by tags is already allowed in projects and experiments. I think we just missed this one key in runs' implementation :P

😅 

>I just double checked and == works too 🤷. Lmk which do you prefer.

`~=` will do just fine

**Pull request merged**
