### PR TITLE
[VR-13024] Event logged for experiment_run resource in local database

### PR DESCRIPTION
**Pull request by anandjakhaniya**
## Impact and Context

**Jira Ticket:** https://vertaai.atlassian.net/browse/VR-13024

- Event logged in local database for project service add/update endpoints

## Testing

- [ ] Deployed the service to dev env
- [ ] Used functionality on dev env 
- [ ] Added unit test(s)
- [ ] Added integration test(s)

### CODE REVIEW

**Review by evgeniilezhnin — COMMENTED** [review]
No addEvent in deleteExperimentRun, deleteExperimentRuns in Future service and service

Also why there is so many same methods in future and regular service? They are used both? Should we delete these methods from regular service to not add events in these methods?

**Review by evgeniilezhnin — APPROVED** [review]
assuming deletion in separate PR

**Review by conradoverta — APPROVED** [review]
I won't review 1.6k LOC =)

Let's see if maybe we can provide less granularity on the events. Otherwise it will also be almost impossible to consume. For example, we can group all "ER updated" into a single event type.

**Review by conradoverta — CHANGES_REQUESTED** [review]
Pressed the wrong button

**Comment by anandjakhaniya** [comment]
> I won't review 1.6k LOC =)
> 
> Let's see if maybe we can provide less granularity on the events. Otherwise it will also be almost impossible to consume. For example, we can group all "ER updated" into a single event type.

You can see document at https://github.com/VertaAI/docs/pull/89 where there is only three event types for run CRUD which is ADD/UPDATE/DELETE .

**Pull request merged**
