### PR TITLE
VR-3438 add sha to commit

### PR DESCRIPTION
**Pull request by evgeniilezhnin**

### CODE REVIEW

**Comment by ravishetye** [comment]
Please provide a description or link to a slack message to set some context for the changes.

**Comment by evgeniilezhnin** [comment]
> Please provide a description or link to a slack message to set some context for the changes.

It's called as a jira ticket: https://vertaai.atlassian.net/browse/VR-3438

**Comment by evgeniilezhnin** [comment]
https://vertaai.slack.com/archives/CJG0NL86B/p1582334077363500

**Comment by conradoverta** [comment]
@evgeniilezhnin this breaks MDB build. Please don't do that.

**Pull request merged**
