### PR TITLE
VR-6022 add user to org

### PR DESCRIPTION
**Pull request by evgeniilezhnin**

### CODE REVIEW

**Review by convoliution — CHANGES_REQUESTED** [review]
Is `share_with` meant to be a new member's email, or username (or both)?
Could you add a comment/docstring to explain what it is? 🙏

**Comment by nhatsmrt** [comment]
Small request: can you add "name" and "id" property to Organization? Previously you returned the message itself, so org.id and org.name are valid and were used in tests + fixtures. It's probably easier to still provide these properties than to fix the tests.

**Comment by evgeniilezhnin** [comment]
> share_with

both. Added

**Comment by evgeniilezhnin** [comment]
> Small request: can you add "name" and "id" property to Organization? Previously you returned the message itself, so org.id and org.name are valid and were used in tests + fixtures. It's probably easier to still provide these properties than to fix the tests.

added

**Review by convoliution — APPROVED** [review]

**Pull request merged**
