### PR TITLE
Couple of minor typos in modeldb.rst

### PR DESCRIPTION
**Pull request by chandra-gh**
Couple of minor typos in modeldb.rst

### CODE REVIEW

**Comment by chandra-gh** [comment]
Hi @convoliution, I fixed a few minor typos in documentation.

**Comment by convoliution** [comment]
@chandra-gh
This is wonderful! Thanks a bunch.

@ravishetye Could you take a quick look at the *Note* added to the root README, and if there's anything else we should add there while we're at it?

**Review by convoliution — APPROVED** [review]

**Comment by chandra-gh** [comment]
You are welcome.

**Review by ravishetye — APPROVED** [review]
Thanks for the changes @chandra-gh

**Review by ravishetye — APPROVED** [review]
Thanks for the changes @chandra-gh . the comment on config for backend makes sense to me and seems useful.

**Pull request merged**
