### PR TITLE
[MRG] travis automatic testing of builds

### PR DESCRIPTION
**Pull request by RogerTangos**
- Automatic testing of scala and python clients in PR's and branches
- Still working on testing the server
- Results at [https://travis-ci.org/mitdbg/modeldb](https://travis-ci.org/mitdbg/modeldb)
- Test status displayed on main README.md

### CODE REVIEW

**Comment by RogerTangos** [comment]
Client tests are passing. I'm still working on the server tests, which can be added in another PR or (if I get done today) updated here.

**Comment by mpvartak** [comment]
Is there a reason why https://travis-ci.org/mitdbg/modeldb says build failing at the moment? i'd have expected it to pass b/c the client tests pass.

**Comment by mpvartak** [comment]
LGTM otherwise.

**Comment by RogerTangos** [comment]
@mpvartak - Before I fixed the travis-ci configuration, it ran the master branch, which didn't have the `.travis.yml` file, so it failed by default. (Sorry about that!) Once this is merged, it should say passing.

**Pull request merged**
