### PR TITLE
read host from syncer.json and pass to __init__

### PR DESCRIPTION
**Pull request by ghost**
Manasi, from our last chat, this enables us to register without scp'ing.

### CODE REVIEW

**Comment by mpvartak** [comment]
@RogerTangos this is related to your config change. Could you please take a look?

**Comment by RogerTangos** [comment]
Hey @arubisov Sorry I didn't get back to you yesterday. 

I'm in the process of making structs for `ConfigUtils` to return. If a host and port aren't specified, we can then use the system-wide defaults in `syncer.json`, instead of having it hardcoded in `ModelDbSyncerBase`

Would this also solve your issue? And could you wait for me to get that PR in? (Probably by the end of the day or early tomorrow)

**Comment by RogerTangos** [comment]
@arubisov - Does #234 solve the problem for you?

**Comment by ghost** [comment]
I'll review it by Monday, but at a glance looks promising! Cheers

**Comment by ghost** [comment]
Solved by #234

**Pull request closed without merging**
