### PR TITLE
VR-5722 Change endpoint.update_from_config to take canary rule names rather than rule_id

### PR DESCRIPTION
**Pull request by nhatsmrt**
@convoliution I believe this is what you are expecting, correct?

### CODE REVIEW

**Comment by convoliution** [comment]
@nhatsmrt I would ask the user for `"rule"` instead of `"parent_name"` in their provided JSON. "Parent name" is just something I'm having the Client use internally for parameters to refer to their parent rules.

**Comment by nhatsmrt** [comment]
> @nhatsmrt I would ask the user for `"rule"` instead of `"parent_name"` in their provided JSON. "Parent name" is just something I'm having the Client use internally for parameters to refer to their parent rules.

Fixed.

**Comment by nhatsmrt** [comment]
Fix another test.

**Review by convoliution — APPROVED** [review]
Thanks Jim!

**Pull request merged**
