### PR TITLE
Update backend to support java 11

### PR DESCRIPTION
**Pull request by coryverta**
Updates the maven configuration for the project to adopt java 11.

### CODE REVIEW

**Comment by evgeniilezhnin** [comment]
It works for me, but have compilation error on jenkins about unknown java version. Maybe an old java version on server?

**Comment by conradoverta** [comment]
Yes, we have java 1.8 in the images I believe. We'll have to install a newer java version.

**Review by evgeniilezhnin — APPROVED** [review]

**Comment by evgeniilezhnin** [comment]
@ad-47 @conradoverta should we merge it?

**Comment by conradoverta** [comment]
Works for me

**Pull request merged**
