### PR TITLE
[VR-13069] Make ModelDB build to Postgres compatible

### PR DESCRIPTION
**Pull request by anandjakhaniya**
## Impact and Context

**Jira Ticket:** https://vertaai.atlassian.net/browse/VR-13069
- Make MDB backend to compatible with Postgres and fix Liquibase tags according to the same as well.

**Note:**
- Please replace `RdbDialect` from `org.hibernate.dialect.PostgreSQLDialect` into `org.hibernate.dialect.PostgreSQL82Dialect` to successfully execute MDB service with postgres. Old dialect was deprecated.
- New DB config should like 
```
database:
  DBType: relational
  timeout: 4
  liquibaseLockThreshold: 60
  RdbConfiguration:
    RdbDatabaseName: modeldb_oss
    RdbDriver: "org.postgresql.Driver"
    RdbDialect: "org.hibernate.dialect.PostgreSQL82Dialect"
    RdbUrl: "jdbc:postgresql://localhost:5432"
    RdbUsername: postgres
    RdbPassword: root
```

## Testing

- [ ] Deployed the service to dev env
- [ ] Used functionality on dev env 
- [ ] Added unit test(s)
- [ ] Added integration test(s)

### CODE REVIEW

**Review by coryverta — APPROVED** [review]

**Comment by coryverta** [comment]
Please regression test against existing mysql databases to ensure successful migration and no hash mismatches

**Review by CaptEmulation — CHANGES_REQUESTED** [review]
Please update the backend/config.yaml and backend/config.example.yaml

**Comment by anandjakhaniya** [comment]
> Please update the backend/config.yaml and backend/config.example.yaml

Added sample oss-config.yaml in repo

**Review by conradoverta — CHANGES_REQUESTED** [review]
The amount of shift in the config makes it hard to review it. Also let's add comment on the code changes as they're not obvious

**Comment by anandjakhaniya** [comment]
This is too much old code and seems like now it is not useful. Also, the Jira ticket is marked as incompleted https://vertaai.atlassian.net/browse/VR-13069 so closing this PR.

**Comment by anandjakhaniya** [comment]
> This is too much old code and seems like now it is not useful. Also, the Jira ticket is marked as incompleted https://vertaai.atlassian.net/browse/VR-13069 so closing this PR.

I have reopened. I feel like it is still useful so investigating more on this.

**Comment by jkwatson-verta** [comment]
closing as this is quite out of date

**Pull request closed without merging**
