### PR TITLE
VR-6056 Use getDatasetVersionById in Client again

### PR DESCRIPTION
**Pull request by nhatsmrt**
This reverts commit 7eb32a9370de6a39e7225e9694158257c020a7b5.

### CODE REVIEW

**Comment by nhatsmrt** [comment]
Running test_datasets.py:

```
============================================================================= 3 failed, 18 passed, 16 skipped in 54.99 seconds =============================================================================
```

The failed ones are S3-related, which I don't have the right authorization.

**Comment by convoliution** [comment]
@nhatsmrt Sorry—I know this is a couple days late, but I'd like to double check: which specific tests failed?
The test summary should say something like
```
FAILED test_model_registry/test_model_version.py::TestDeployability::test_download_docker_context
```

And also ideally, what was the actual error message? I'm assuming it's something about credentials not being found, but I'd like to be sure.

**Comment by nhatsmrt** [comment]
> @nhatsmrt Sorry—I know this is a couple days late, but I'd like to double check: which specific tests failed?
> The test summary should say something like
> 
> ```
> FAILED test_model_registry/test_model_version.py::TestDeployability::test_download_docker_context
> ```
> 
> And also ideally, what was the actual error message? I'm assuming it's something about credentials not being found, but I'd like to be sure.

Yeah iirc it was credentials, but let me just re run those tests. Can't be too certain these days.

**Comment by nhatsmrt** [comment]
This is the full error message:

```
test_datasets.py ..ssss......s...sss..ss..No handlers could be found for logger "tensorflow"
FF.F..ssssss                                                                                                                                               [100%]

================================================================================================= FAILURES =================================================================================================
_______________________________________________________________________________ TestS3DatasetVersionInfo.test_single_object ________________________________________________________________________________

self = <tests.test_datasets.TestS3DatasetVersionInfo instance at 0x1119c71e0>, s3_bucket = 'bucket', s3_object = 'object'

    def test_single_object(self, s3_bucket, s3_object):
        botocore = pytest.importorskip("botocore")
    
        try:
>           s3dvi = S3DatasetVersionInfo(s3_bucket, s3_object)

test_datasets.py:396: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../verta/_dataset.py:772: in __init__
    self.dataset_part_infos = self.get_dataset_part_infos()
../verta/_dataset.py:784: in get_dataset_part_infos
    obj = conn.head_object(Bucket=self.bucket_name, Key=self.key)
../venv/lib/python2.7/site-packages/botocore/client.py:316: in _api_call
    return self._make_api_call(operation_name, kwargs)
../venv/lib/python2.7/site-packages/botocore/client.py:622: in _make_api_call
    operation_model, request_dict, request_context)
../venv/lib/python2.7/site-packages/botocore/client.py:641: in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
../venv/lib/python2.7/site-packages/botocore/endpoint.py:102: in make_request
    return self._send_request(request_dict, operation_model)
../venv/lib/python2.7/site-packages/botocore/endpoint.py:132: in _send_request
    request = self.create_request(request_dict, operation_model)
../venv/lib/python2.7/site-packages/botocore/endpoint.py:116: in create_request
    operation_name=operation_model.name)
../venv/lib/python2.7/site-packages/botocore/hooks.py:356: in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
../venv/lib/python2.7/site-packages/botocore/hooks.py:228: in emit
    return self._emit(event_name, kwargs)
../venv/lib/python2.7/site-packages/botocore/hooks.py:211: in _emit
    response = handler(**kwargs)
../venv/lib/python2.7/site-packages/botocore/signers.py:90: in handler
    return self.sign(operation_name, request)
../venv/lib/python2.7/site-packages/botocore/signers.py:160: in sign
    auth.add_auth(request)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <botocore.auth.S3SigV4Auth object at 0x134958510>, request = <botocore.awsrequest.AWSRequest object at 0x135579390>

    def add_auth(self, request):
        if self.credentials is None:
>           raise NoCredentialsError
E           NoCredentialsError: Unable to locate credentials

../venv/lib/python2.7/site-packages/botocore/auth.py:357: NoCredentialsError
___________________________________________________________________________________ TestS3DatasetVersionInfo.test_bucket ___________________________________________________________________________________

self = <tests.test_datasets.TestS3DatasetVersionInfo instance at 0x138e45eb0>, s3_bucket = 'bucket'

    def test_bucket(self, s3_bucket):
        botocore = pytest.importorskip("botocore")
    
        try:
>           s3dvi = S3DatasetVersionInfo(s3_bucket)

test_datasets.py:406: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../verta/_dataset.py:772: in __init__
    self.dataset_part_infos = self.get_dataset_part_infos()
../verta/_dataset.py:792: in get_dataset_part_infos
    for obj in conn.list_objects(Bucket=self.bucket_name)['Contents']:
../venv/lib/python2.7/site-packages/botocore/client.py:316: in _api_call
    return self._make_api_call(operation_name, kwargs)
../venv/lib/python2.7/site-packages/botocore/client.py:622: in _make_api_call
    operation_model, request_dict, request_context)
../venv/lib/python2.7/site-packages/botocore/client.py:641: in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
../venv/lib/python2.7/site-packages/botocore/endpoint.py:102: in make_request
    return self._send_request(request_dict, operation_model)
../venv/lib/python2.7/site-packages/botocore/endpoint.py:132: in _send_request
    request = self.create_request(request_dict, operation_model)
../venv/lib/python2.7/site-packages/botocore/endpoint.py:116: in create_request
    operation_name=operation_model.name)
../venv/lib/python2.7/site-packages/botocore/hooks.py:356: in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
../venv/lib/python2.7/site-packages/botocore/hooks.py:228: in emit
    return self._emit(event_name, kwargs)
../venv/lib/python2.7/site-packages/botocore/hooks.py:211: in _emit
    response = handler(**kwargs)
../venv/lib/python2.7/site-packages/botocore/signers.py:90: in handler
    return self.sign(operation_name, request)
../venv/lib/python2.7/site-packages/botocore/signers.py:160: in sign
    auth.add_auth(request)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <botocore.auth.S3SigV4Auth object at 0x138c8a450>, request = <botocore.awsrequest.AWSRequest object at 0x138c8a110>

    def add_auth(self, request):
        if self.credentials is None:
>           raise NoCredentialsError
E           NoCredentialsError: Unable to locate credentials

../venv/lib/python2.7/site-packages/botocore/auth.py:357: NoCredentialsError
__________________________________________________________________________ TestS3ClientFunctions.test_s3_dataset_version_creation __________________________________________________________________________

self = <tests.test_datasets.TestS3ClientFunctions instance at 0x138ca0820>, client = <verta.client.Client object at 0x138ea4450>, s3_bucket = 'bucket'
created_datasets = [<S3Dataset "Dataset 79379159794070375">]

    def test_s3_dataset_version_creation(self, client, s3_bucket, created_datasets):
        botocore = pytest.importorskip("botocore")
    
        try:
            dataset = client.set_dataset(type="s3")
            created_datasets.append(dataset)
>           dataset_version = dataset.create_version(s3_bucket)

test_datasets.py:429: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../verta/_dataset.py:282: in create_version
    version_info = S3DatasetVersionInfo(bucket_name, key=key, key_prefix=key_prefix, url_stub=url_stub)
../verta/_dataset.py:772: in __init__
    self.dataset_part_infos = self.get_dataset_part_infos()
../verta/_dataset.py:792: in get_dataset_part_infos
    for obj in conn.list_objects(Bucket=self.bucket_name)['Contents']:
../venv/lib/python2.7/site-packages/botocore/client.py:316: in _api_call
    return self._make_api_call(operation_name, kwargs)
../venv/lib/python2.7/site-packages/botocore/client.py:622: in _make_api_call
    operation_model, request_dict, request_context)
../venv/lib/python2.7/site-packages/botocore/client.py:641: in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
../venv/lib/python2.7/site-packages/botocore/endpoint.py:102: in make_request
    return self._send_request(request_dict, operation_model)
../venv/lib/python2.7/site-packages/botocore/endpoint.py:132: in _send_request
    request = self.create_request(request_dict, operation_model)
../venv/lib/python2.7/site-packages/botocore/endpoint.py:116: in create_request
    operation_name=operation_model.name)
../venv/lib/python2.7/site-packages/botocore/hooks.py:356: in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
../venv/lib/python2.7/site-packages/botocore/hooks.py:228: in emit
    return self._emit(event_name, kwargs)
../venv/lib/python2.7/site-packages/botocore/hooks.py:211: in _emit
    response = handler(**kwargs)
../venv/lib/python2.7/site-packages/botocore/signers.py:90: in handler
    return self.sign(operation_name, request)
../venv/lib/python2.7/site-packages/botocore/signers.py:160: in sign
    auth.add_auth(request)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <botocore.auth.S3SigV4Auth object at 0x1355ccf50>, request = <botocore.awsrequest.AWSRequest object at 0x1355ccb10>

    def add_auth(self, request):
        if self.credentials is None:
>           raise NoCredentialsError
E           NoCredentialsError: Unable to locate credentials

../venv/lib/python2.7/site-packages/botocore/auth.py:357: NoCredentialsError
------------------------------------------------------------------------------------------ Captured stdout setup -------------------------------------------------------------------------------------------
[TEST LOG] test setup begun 2020-08-20 16:25:03.389311 UTC
[DEBUG] using email: nphamcs@gmail.com
[DEBUG] using developer key: 0a45e0bf-****-****-****-************
connection successfully established
------------------------------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------------------------------
created new Dataset: Dataset 79379159794070375 in personal workspace
----------------------------------------------------------------------------------------- Captured stdout teardown -----------------------------------------------------------------------------------------
[TEST LOG] test teardown completed 2020-08-20 16:25:05.220631 UTC
============================================================================= 3 failed, 18 passed, 16 skipped in 58.97 seconds =============================================================================
```

**Comment by convoliution** [comment]
Cool, looks good to me.

**Review by convoliution — APPROVED** [review]

**Pull request merged**
