### PR TITLE
Frontend fixes

### PR DESCRIPTION
**Pull request by ghost**
See #222 and #223

### CODE REVIEW

**Comment by mpvartak** [comment]
Looks good. @weienlee can you take a quick look?

**Comment by weienlee** [comment]
Also looks good to me.

**Comment by RogerTangos** [comment]
Hey @arubisov - Looks good. Thanks!

For the next one, could you prefix your branch with [WIP] for Work in Progress or [MRG] for ready to merge a la [CONTRIBUTING.md](https://github.com/mitdbg/modeldb/blob/master/CONTRIBUTING.md)?

**Comment by ghost** [comment]
Will do!

**Pull request merged**
