### PR TITLE
fix: docker compose for mysql [copy of external PR]

### PR DESCRIPTION
**Pull request by jkwatson-verta**
## Impact and Context

Duplicate of #4210 in hopes that CI will run properly. 
/cc @amammad 

## Risks and Area of Effect
- [ ] Is this a breaking change?

## Testing
- [ ] Unit test
- [ ] Deployed to dev env
- [ ] Other (explain) 

## Reverting
- [ ] Contains Migration - _Do Not Revert_

### CODE REVIEW

**Review by marcelo-verta-ai — APPROVED** [review]

**Comment by jkwatson-verta** [comment]
@amammad this doesn't quite right for me on my mac laptop. I get lots of errors from the backend about not being able to load the driver class. Any ideas?

**Review by marcelo-verta-ai — APPROVED** [review]

**Comment by am0o0** [comment]
this works fine for me when I'm using `docker-compose-all-mysql.yaml` with a local version of `vertaaiofficial/modeldb-backend`
 
has `vertaaiofficial/modeldb-backend:2.0.8.1` been updated now from my previous merged PR? I can test issue this if it is updated.

**Comment by jkwatson-verta** [comment]
> this works fine for me when I'm using `docker-compose-all-mysql.yaml` with a local version of `vertaaiofficial/modeldb-backend`
> 
> has `vertaaiofficial/modeldb-backend:2.0.8.1` been updated now from my previous merged PR? I can test issue this if it is updated.

TBH, I don't even know what generates that image. 🤔

**Comment by am0o0** [comment]
then I think I should create a docker file to build the backend locally, then use the new docker image within this docker-compose each time.

**Review by gustavoteixeirah — APPROVED** [review]

**Comment by jkwatson-verta** [comment]
> > this works fine for me when I'm using `docker-compose-all-mysql.yaml` with a local version of `vertaaiofficial/modeldb-backend`
> > has `vertaaiofficial/modeldb-backend:2.0.8.1` been updated now from my previous merged PR? I can test issue this if it is updated.
> 
> TBH, I don't even know what generates that image. 🤔

Looks like there's a script in the repo to publish, but I'm pretty sure we're not doing this automatically (or even manually) any more.

**Comment by jkwatson-verta** [comment]
@amammad I'm going to go ahead and merge this. good luck!

**Pull request merged**
