### PR TITLE
Remove workflows/ directory

### PR DESCRIPTION
**Pull request by convoliution**
## Impact and Context

With our example notebooks now being hosted in https://github.com/VertaAI/examples, this directory is no longer being maintained. This PR removes it, and updates links/references accordingly.

## Risks and Area of Effect

Moderate risk and AoE: I have made a careful effort to update links/references under our control to this directory (see PRs mentioning this PR, below), though there may be old links out in the wild (Slack, GitHub Issues, etc.) that refer to it.

## Testing

—

## How to Revert

Revert this PR.

### CODE REVIEW

**Comment by convoliution** [comment]
!rebuild

**Comment by convoliution** [comment]
!rebuild

**Comment by convoliution** [comment]
!rebuild

**Comment by convoliution** [comment]
!rebuild

**Review by MeetaDash — APPROVED** [review]

**Pull request merged**
