### PR TITLE
Support docker compose for mysql, fix config.yaml

### PR DESCRIPTION
**Pull request by am0o0**
## Impact and Context
I created a new current Docker compose file to use MySQL, also the main config file of `backend` has been updated.
this PR depends on my previous [PR](https://github.com/VertaAI/modeldb/pull/4209) to solve some bugs from modeldb.

### CODE REVIEW

**Comment by am0o0** [comment]
@jkwatson-verta could you please check this PR?

**Comment by am0o0** [comment]
@jkwatson I'm sorry for mentioning you again with your other account!

**Comment by jkwatson-verta** [comment]
> @jkwatson I'm sorry for mentioning you again with your other account!

no worries. I was on vacation last week, but I'm looking now.

**Comment by jkwatson-verta** [comment]
@amammad Our CI doesn't seem to run on your fork. Do you mind if I resubmit this in our fork directly, so CI can run on it?

**Comment by am0o0** [comment]
>Do you mind if I resubmit this in our fork directly, so CI can run on it?

Yes, NP at all.

**Comment by jkwatson-verta** [comment]
> > Do you mind if I resubmit this in our fork directly, so CI can run on it?
> 
> Yes, NP at all.

https://github.com/VertaAI/modeldb/pull/4228

**Pull request closed without merging**
