### PR TITLE
VR-5851 attribute CRUD

### PR DESCRIPTION
**Pull request by evgeniilezhnin**

### CODE REVIEW

**Review by convoliution — APPROVED** [review]
This seems right to me; we'll see if there is a backend bug or not.

**Comment by evgeniilezhnin** [comment]
There's a deletion bug: https://vertaai.slack.com/archives/C016QL3TEUT/p1597322605034600

**Review by convoliution — APPROVED** [review]
Attribute creation is blocking VR-5848, so I am approving this for now. We can follow up on the bugs later.

Because there seems to be a bug with deletion, **please comment out ModelVersion.del_attribute()** since it does not work, before merging.

**Comment by evgeniilezhnin** [comment]
> Attribute creation is blocking VR-5848, so I am approving this for now. We can follow up on the bugs later.
> 
> Because there seems to be a bug with deletion, **please comment out ModelVersion.del_attribute()** since it does not work, before merging.

seem to work on aj.dev after fix

**Pull request merged**
