### PR TITLE
[VUMM-793] Permission v2 changes for Dataset Service

### PR DESCRIPTION
**Pull request by anandjakhaniya**
## Testing
- [ ] Unit test
- [ ] Deployed to dev env
- [ ] Other (explain) 

## Reverting
- [ ] Contains Migration - _Do Not Revert_

### CODE REVIEW

**Comment by anandjakhaniya** [comment]
I don't know why DatasetTest is flakey with the Mockito. So currently working on it, please let me know if you have any suggestions for this flakiness. @evgeniilezhnin @eheinlein-verta

**Comment by evgeniilezhnin** [comment]
> I don't know why DatasetTest is flakey with the Mockito. So currently working on it, please let me know if you have any suggestions for this flakiness. @evgeniilezhnin @eheinlein-verta

I tried this: https://stackoverflow.com/a/15560154, also I tried replacing to doReturn-when in dataset test. but I still get mockito stubbing errors sometimes
Could you replace when-thenReturn with doReturn-when everywhere? I mean in DatasetTest.java and in every method from ModeldbTestSetup.java which dataset test calls (probably better all ModeldbTestSetup.java file). For example write some script to do it or macros in IDE, vim or emacs. Or manually if there is not much changes needed

**Comment by eheinlein-verta** [comment]
Where does this PR stand?

**Review by evgeniilezhnin — APPROVED** [review]

**Comment by evgeniilezhnin** [comment]
> Where does this PR stand?

I think it is also blocked on the issues with UAC h2 mocks, but this PR probably should fix it: https://github.com/VertaAI/modeldb/pull/3482

**Pull request merged**
