### PR TITLE
VR-5553 Implement Autoscaling class

### PR DESCRIPTION
**Pull request by nhatsmrt**
Testing will be done in https://github.com/VertaAI/modeldb/pull/1174

### CODE REVIEW

**Review by convoliution — APPROVED** [review]
@nhatsmrt Were you able to test this? If not, would you prefer merging it in and potentially revisiting it later, or holding it open until the deployment backend is fully ready?

**Comment by nhatsmrt** [comment]
> @nhatsmrt Were you able to test this? If not, would you prefer merging it in and potentially revisiting it later, or holding it open until the deployment backend is fully ready?

I think I would feel better if we hold it open until backend is ready and I can actually test it, if you don't mind me bothering you later about merging PRs =))

**Comment by nhatsmrt** [comment]
@convoliution Would you mind double-checking the input validation again :( I just added a bunch of checks. Thanks!

**Comment by nhatsmrt** [comment]
Validation rule removed.

**Comment by convoliution** [comment]
@nhatsmrt Is this in a good state to review and potentially merge?

**Comment by nhatsmrt** [comment]
Yep.

**Pull request merged**
