### PR TITLE
refactor!: [cat-73] Rename attribute Action Type to Task Type

### PR DESCRIPTION
**Pull request by marcelo-verta-ai**
# Summary

Rename column action_type to task_type

# References

https://vertaai.atlassian.net/browse/CAT-73?atlOrigin=eyJpIjoiMDYwZWJiYTIwMDI1NGY4MzliMGU5YWJiYjdhMjZiZjEiLCJwIjoiaiJ9

# Dependencies

https://vertaai.atlassian.net/browse/CAT-70?atlOrigin=eyJpIjoiZjc2NjU1Y2MwOWJhNDQ3NWEyMWQzYTViYjU5ZjNmMzYiLCJwIjoiaiJ9

# Test Result (2022-08-29)
```
export VERTA_HOST="https://modelcatalog.dev.verta.ai/"
export VERTA_EMAIL="marcelo@verta.ai"
export VERTA_DEV_KEY="7ae98d72-d0dd-4034-9fb1-e2f79e894fd9"
pytest-3 -k "TestTaskTypes or TestDataTypes" -vvra      
================================================================================== test session starts ===================================================================================
platform linux -- Python 3.8.10, pytest-4.6.9, py-1.8.1, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> suppress_health_check=[HealthCheck.too_slow], database=DirectoryBasedExampleDatabase('/opt/repositorio-git/verta/modeldb/client/verta/tests/.hypothesis/examples')
rootdir: /opt/repositorio-git/verta/modeldb/client/verta/tests, inifile: pytest.ini
plugins: hypothesis-4.36.2
collected 1342 items / 1297 deselected / 3 skipped / 42 selected                                                                                                                         

registry/test_model.py::TestTaskTypes::test_creation[Classification] PASSED                                                                                                        [  2%]
registry/test_model.py::TestTaskTypes::test_creation[Clustering] PASSED                                                                                                            [  4%]
registry/test_model.py::TestTaskTypes::test_creation[Detection] PASSED                                                                                                             [  6%]
registry/test_model.py::TestTaskTypes::test_creation[Other] PASSED                                                                                                                 [  8%]
registry/test_model.py::TestTaskTypes::test_creation[Regression] PASSED                                                                                                            [ 11%]
registry/test_model.py::TestTaskTypes::test_creation[Transcription] PASSED                                                                                                         [ 13%]
registry/test_model.py::TestTaskTypes::test_creation[Translation] PASSED                                                                                                           [ 15%]
registry/test_model.py::TestTaskTypes::test_creation[_Unknown] SKIPPED                                                                                                             [ 17%]
registry/test_model.py::TestTaskTypes::test_set[Classification] PASSED                                                                                                             [ 20%]
registry/test_model.py::TestTaskTypes::test_set[Clustering] PASSED                                                                                                                 [ 22%]
registry/test_model.py::TestTaskTypes::test_set[Detection] PASSED                                                                                                                  [ 24%]
registry/test_model.py::TestTaskTypes::test_set[Other] PASSED                                                                                                                      [ 26%]
registry/test_model.py::TestTaskTypes::test_set[Regression] PASSED                                                                                                                 [ 28%]
registry/test_model.py::TestTaskTypes::test_set[Transcription] PASSED                                                                                                              [ 31%]
registry/test_model.py::TestTaskTypes::test_set[Translation] PASSED                                                                                                                [ 33%]
registry/test_model.py::TestTaskTypes::test_set[_Unknown] SKIPPED                                                                                                                  [ 35%]
registry/test_model.py::TestDataTypes::test_creation[Audio] PASSED                                                                                                                 [ 37%]
registry/test_model.py::TestDataTypes::test_creation[Image] PASSED                                                                                                                 [ 40%]
registry/test_model.py::TestDataTypes::test_creation[Other] PASSED                                                                                                                 [ 42%]
registry/test_model.py::TestDataTypes::test_creation[Tabular] PASSED                                                                                                               [ 44%]
registry/test_model.py::TestDataTypes::test_creation[Text] PASSED                                                                                                                  [ 46%]
registry/test_model.py::TestDataTypes::test_creation[Video] PASSED                                                                                                                 [ 48%]
registry/test_model.py::TestDataTypes::test_creation[_Unknown] SKIPPED                                                                                                             [ 51%]
registry/test_model.py::TestDataTypes::test_set[Audio] PASSED                                                                                                                      [ 53%]
registry/test_model.py::TestDataTypes::test_set[Image] PASSED                                                                                                                      [ 55%]
registry/test_model.py::TestDataTypes::test_set[Other] PASSED                                                                                                                      [ 57%]
registry/test_model.py::TestDataTypes::test_set[Tabular] PASSED                                                                                                                    [ 60%]
registry/test_model.py::TestDataTypes::test_set[Text] PASSED                                                                                                                       [ 62%]
registry/test_model.py::TestDataTypes::test_set[Video] PASSED                                                                                                                      [ 64%]
registry/test_model.py::TestDataTypes::test_set[_Unknown] SKIPPED                                                                                                                  [ 66%]
test_cli/test_registry.py::TestTaskTypes::test_creation[Classification] PASSED                                                                                                     [ 68%]
test_cli/test_registry.py::TestTaskTypes::test_creation[Clustering] PASSED                                                                                                         [ 71%]
test_cli/test_registry.py::TestTaskTypes::test_creation[Detection] PASSED                                                                                                          [ 73%]
test_cli/test_registry.py::TestTaskTypes::test_creation[Other] PASSED                                                                                                              [ 75%]
test_cli/test_registry.py::TestTaskTypes::test_creation[Regression] PASSED                                                                                                         [ 77%]
test_cli/test_registry.py::TestTaskTypes::test_creation[Transcription] PASSED                                                                                                      [ 80%]
test_cli/test_registry.py::TestTaskTypes::test_creation[Translation] PASSED                                                                                                        [ 82%]
test_cli/test_registry.py::TestTaskTypes::test_creation[_Unknown] SKIPPED                                                                                                          [ 84%]
test_cli/test_registry.py::TestDataTypes::test_creation[Audio] PASSED                                                                                                              [ 86%]
test_cli/test_registry.py::TestDataTypes::test_creation[Image] PASSED                                                                                                              [ 88%]
test_cli/test_registry.py::TestDataTypes::test_creation[Other] PASSED                                                                                                              [ 91%]
test_cli/test_registry.py::TestDataTypes::test_creation[Tabular] PASSED                                                                                                            [ 93%]
test_cli/test_registry.py::TestDataTypes::test_creation[Text] PASSED                                                                                                               [ 95%]
test_cli/test_registry.py::TestDataTypes::test_creation[Video] PASSED                                                                                                              [ 97%]
test_cli/test_registry.py::TestDataTypes::test_creation[_Unknown] SKIPPED                                                                                                          [100%]

================================================================================ short test summary info =================================================================================
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/test_backend.py:9: reduce DB pressure to establish test baseline
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/test_datasets.py:4: outdated tests for legacy API
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/test_cli/test_repository.py:11: repository sub-CLI has been disabled
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/registry/test_model.py:140: unsupported task type
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/registry/test_model.py:153: unsupported task type
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/registry/test_model.py:166: unsupported data type
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/registry/test_model.py:179: unsupported data type
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/test_cli/test_registry.py:679: unsupported task type
SKIPPED [1] /opt/repositorio-git/verta/modeldb/client/verta/tests/test_cli/test_registry.py:703: unsupported data type
================================================================ 39 passed, 9 skipped, 1297 deselected in 214.81 seconds =================================================================
```

### CODE REVIEW

**Review by liuverta — COMMENTED** [review]
When the dependency is ready, please also make sure to run the tests like last time!

**Comment by marcelo-verta-ai** [comment]
> When the dependency is ready, please also make sure to run the tests like last time!

When the dependecy is ready, even branch not merged into main, Can I merge branch into this branch, make a test and push it (includind branch) to PR again ?

**Comment by liuverta** [comment]
Hmmm maybe, but I think it would be better to first have the protobuf dependency merged into main, then merge main into this branch, then run the

```sh
pytest -k "TestTaskTypes or TestDataTypes" -vvra
```

tests on this branch.

**Comment by liuverta** [comment]
!rebuild

**Comment by liuverta** [comment]
@marcelo-verta-ai Would you mind running `git merge main` into this branch?

**Comment by marcelo-verta-ai** [comment]
> @marcelo-verta-ai Would you mind running `git merge main` into this branch?

sure ... no worries...  But I did it before tests.

My terminal

```
marcelo@marcelo-Vostro-5402:/opt/repositorio-git/verta/modeldb$ git branch
  main
  marcelo/cat-48
* marcelo/cat-73
marcelo@marcelo-Vostro-5402:/opt/repositorio-git/verta/modeldb$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
marcelo@marcelo-Vostro-5402:/opt/repositorio-git/verta/modeldb$ git pull
Enter passphrase for key '/home/marcelo/.ssh/id_ed25519': 
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 7 (delta 5), reused 7 (delta 5), pack-reused 0
Unpacking objects: 100% (7/7), 1.15 KiB | 392.00 KiB/s, done.
From github.com:VertaAI/modeldb
 * [new branch]          liu/dummy-org -> origin/liu/dummy-org
Already up to date.
Current branch main is up to date.
marcelo@marcelo-Vostro-5402:/opt/repositorio-git/verta/modeldb$ git checkout marcelo/cat-73
Switched to branch 'marcelo/cat-73'
Your branch is ahead of 'origin/marcelo/cat-73' by 9 commits.
  (use "git push" to publish your local commits)
marcelo@marcelo-Vostro-5402:/opt/repositorio-git/verta/modeldb$ git merge main
Already up to date.
marcelo@marcelo-Vostro-5402:/opt/repositorio-git/verta/modeldb$ git status
On branch marcelo/cat-73
Your branch is ahead of 'origin/marcelo/cat-73' by 9 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
marcelo@marcelo-Vostro-5402:/opt/repositorio-git/verta/modeldb$ git push
Enter passphrase for key '/home/marcelo/.ssh/id_ed25519': 
Enumerating objects: 19, done.
Counting objects: 100% (16/16), done.
Delta compression using up to 8 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 1.76 KiB | 1.76 MiB/s, done.
Total 7 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To github.com:VertaAI/modeldb.git
   8bc5fe95b..135567f6b  marcelo/cat-73 -> marcelo/cat-73

**Review by liuverta — APPROVED** [review]
Looks great! I will merge this. Thank you, @marcelo-verta-ai

**Comment by marcelo-verta-ai** [comment]
> Looks great! I will merge this. Thank you, @marcelo-verta-ai

Sounds good !! Thanks ! @liuverta

**Pull request merged**
