### PR TITLE
Check entity exists with name into workspace using UAC

### PR DESCRIPTION
**Pull request by anandjakhaniya**

### CODE REVIEW

**Comment by conradoverta** [comment]
@ad-47 ~is this still in WIP?~ nevermind. I read 14 days instead of 14 hours!

**Comment by anandjakhaniya** [comment]
@conradoverta This is in WIP because the `resource_name` is not added in `GetResources` endpoint and also the UAC implementation is pending.

**Comment by conradoverta** [comment]
> @conradoverta This is in WIP because the `resource_name` is not added in `GetResources` endpoint and also the UAC implementation is pending.

Yeah, it's fine. I read "14 days" and thought the PR had been replaced by another. My bad!

**Comment by anandjakhaniya** [comment]
this is too old and now this is not needed with newer implementation so closing this.

**Pull request closed without merging**
