### PR TITLE
Find ER with Ids only flag

### PR DESCRIPTION
**Pull request by anandjakhaniya**

### CODE REVIEW

**Review by conradoverta — APPROVED** [review]
Is this option actually used by anything? I'm pretty sure it isn't.

**Comment by anandjakhaniya** [comment]
> Is this option actually used by anything? I'm pretty sure it isn't.

i do not understand this question. Could you elaborate more please??

**Comment by conradoverta** [comment]
> > Is this option actually used by anything? I'm pretty sure it isn't.
> 
> i do not understand this question. Could you elaborate more please??

Can we ask the client and webapp folks if they use this? If not, I'd rather remove this functionality. I don't think anywhere uses it

**Comment by anandjakhaniya** [comment]
> > > Is this option actually used by anything? I'm pretty sure it isn't.
> > 
> > 
> > i do not understand this question. Could you elaborate more please??
> 
> Can we ask the client and webapp folks if they use this? If not, I'd rather remove this functionality. I don't think anywhere uses it

Confirm that in slack https://vertaai.slack.com/archives/CJG0NL86B/p1619759633302900, it is not used by client and webapp and safe to remove it.

**Comment by conradoverta** [comment]
> > > > Is this option actually used by anything? I'm pretty sure it isn't.
> > > 
> > > 
> > > i do not understand this question. Could you elaborate more please??
> > 
> > 
> > Can we ask the client and webapp folks if they use this? If not, I'd rather remove this functionality. I don't think anywhere uses it
> 
> Confirm that in slack https://vertaai.slack.com/archives/CJG0NL86B/p1619759633302900, it is not used by client and webapp and safe to remove it.

Then we should probably close this PR and remove the field from the protos

**Pull request closed without merging**
