### PR TITLE
[VUMM-214] Modified logic for untrusted artifacts

### PR DESCRIPTION
**Pull request by anandjakhaniya**
## Impact and Context

Reopen with fixes after reverting PR: https://github.com/VertaAI/modeldb/pull/2925

### CODE REVIEW

**Review by conradoverta — COMMENTED** [review]
Same question as for UAC

**Review by liuverta — APPROVED** [review]
Approved, assuming Conrado's question is addressed.

Also see https://github.com/VertaAI/registry/pull/1060#pullrequestreview-903815620

**Comment by anandjakhaniya** [comment]
> Same question as for UAC

https://github.com/VertaAI/registry/pull/1060#discussion_r822288091

**Review by liuverta — CHANGES_REQUESTED** [review]
See bugs in https://github.com/VertaAI/registry/pull/1060#pullrequestreview-905085407

**Comment by anandjakhaniya** [comment]
> See bugs in [VertaAI/registry#1060 (review)](https://github.com/VertaAI/registry/pull/1060#pullrequestreview-905085407)

That bug was registry only.

**Review by liuverta — APPROVED** [review]

**Pull request merged**
