### PR TITLE
Rs/role service opt

### PR DESCRIPTION
**Pull request by ravishetye**
making the calls to Role service for hydration in parallel

### CODE REVIEW

**Comment by evgeniilezhnin** [comment]
ai/verta/modeldb/HydratedServiceOrgTeamTest.java:296 needs changes: add parameter to getResourceCollaborators call

**Comment by evgeniilezhnin** [comment]
There is an NPE when calling ai.verta.modeldb.HydratedServiceTest#findHydratedDatasetsTest:

"file":"AuthServiceChannel.java","line":102

{"thread":"main","level":"WARN","loggerName":"ai.verta.modeldb.advancedService.AdvancedServiceImpl","message":"null","thrown":{"commonElementCount":0,"name":"java.lang.NullPointerException","cause":{"commonElementCount":0,"localizedMessage":"null","message":"null","name":"java.lang.NullPointerException","extendedStackTrace":[{"class":"com.google.common.base.Preconditions","method":"checkNotNull","file":"Preconditions.java","line":906,"exact":false,"location":"guava-26.0-android.jar","version":"?"},{"class":"io.grpc.stub.MetadataUtils$HeaderAttachingClientInterceptor","method":"<init>","file":"MetadataUtils.java","line":68,"exact":false,"location":"grpc-stub-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.stub.MetadataUtils","method":"newAttachHeadersInterceptor","file":"MetadataUtils.java","line":59,"exact":false,"location":"grpc-stub-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.stub.MetadataUtils","method":"attachHeaders","file":"MetadataUtils.java","line":49,"exact":false,"location":"grpc-stub-1.16.1.jar","version":"1.16.1"},{"class":"ai.verta.modeldb.authservice.AuthServiceChannel","method":"initAuthzServiceStubChannel","file":"AuthServiceChannel.java","line":102,"exact":false,"location":"classes/","version":"?"},{"class":"ai.verta.modeldb.authservice.AuthServiceChannel","method":"getAuthzServiceBlockingStub","file":"AuthServiceChannel.java","line":109,"exact":false,"location":"classes/","version":"?"},{"class":"ai.verta.modeldb.authservice.RoleServiceUtils","method":"getCollaborators","file":"RoleServiceUtils.java","line":345,"exact":false,"location":"classes/","version":"?"},{"class":"ai.verta.modeldb.authservice.RoleServiceUtils","method":"getCollaborators","file":"RoleServiceUtils.java","line":408,"exact":false,"location":"classes/","version":"?"},{"class":"ai.verta.modeldb.authservice.RoleServiceUtils","method":"getResourceCollaborators","file":"RoleServiceUtils.java","line":301,"exact":false,"location":"classes/","version":"?"},{"class":"ai.verta.modeldb.advancedService.AdvancedServiceImpl","method":"lambda$getHydratedDatasets$2","file":"AdvancedServiceImpl.java","line":1180,"exact":false,"location":"classes/","version":"?"},{"class":"java.util.stream.ForEachOps$ForEachOp$OfRef","method":"accept","file":"ForEachOps.java","line":183,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.ArrayList$ArrayListSpliterator","method":"forEachRemaining","file":"ArrayList.java","line":1382,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.stream.AbstractPipeline","method":"copyInto","file":"AbstractPipeline.java","line":482,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.stream.ForEachOps$ForEachTask","method":"compute","file":"ForEachOps.java","line":290,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.concurrent.CountedCompleter","method":"exec","file":"CountedCompleter.java","line":731,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.concurrent.ForkJoinTask","method":"doExec","file":"ForkJoinTask.java","line":289,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.concurrent.ForkJoinPool$WorkQueue","method":"runTask","file":"ForkJoinPool.java","line":1056,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.concurrent.ForkJoinPool","method":"runWorker","file":"ForkJoinPool.java","line":1692,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.concurrent.ForkJoinWorkerThread","method":"run","file":"ForkJoinWorkerThread.java","line":157,"exact":false,"location":"?","version":"1.8.0_242"}]},"extendedStackTrace":[{"class":"sun.reflect.NativeConstructorAccessorImpl","method":"newInstance0","file":"NativeConstructorAccessorImpl.java","line":-2,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"sun.reflect.NativeConstructorAccessorImpl","method":"newInstance","file":"NativeConstructorAccessorImpl.java","line":62,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"sun.reflect.DelegatingConstructorAccessorImpl","method":"newInstance","file":"DelegatingConstructorAccessorImpl.java","line":45,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.lang.reflect.Constructor","method":"newInstance","file":"Constructor.java","line":423,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.concurrent.ForkJoinTask","method":"getThrowableException","file":"ForkJoinTask.java","line":598,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.concurrent.ForkJoinTask","method":"reportException","file":"ForkJoinTask.java","line":677,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.concurrent.ForkJoinTask","method":"invoke","file":"ForkJoinTask.java","line":735,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.stream.ForEachOps$ForEachOp","method":"evaluateParallel","file":"ForEachOps.java","line":159,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.stream.ForEachOps$ForEachOp$OfRef","method":"evaluateParallel","file":"ForEachOps.java","line":173,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.stream.AbstractPipeline","method":"evaluate","file":"AbstractPipeline.java","line":233,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.stream.ReferencePipeline","method":"forEach","file":"ReferencePipeline.java","line":485,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.util.stream.ReferencePipeline$Head","method":"forEach","file":"ReferencePipeline.java","line":650,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"ai.verta.modeldb.advancedService.AdvancedServiceImpl","method":"getHydratedDatasets","file":"AdvancedServiceImpl.java","line":1175,"exact":false,"location":"classes/","version":"?"},{"class":"ai.verta.modeldb.advancedService.AdvancedServiceImpl","method":"findHydratedDatasets","file":"AdvancedServiceImpl.java","line":1243,"exact":false,"location":"classes/","version":"?"},{"class":"ai.verta.modeldb.advancedService.AdvancedServiceImpl","method":"findHydratedDatasets","file":"AdvancedServiceImpl.java","line":1261,"exact":true,"location":"classes/","version":"?"},{"class":"ai.verta.modeldb.HydratedServiceGrpc$MethodHandlers","method":"invoke","file":"HydratedServiceGrpc.java","line":1891,"exact":true,"location":"classes/","version":"?"},{"class":"io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener","method":"onHalfClose","file":"ServerCalls.java","line":171,"exact":true,"location":"grpc-stub-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.PartialForwardingServerCallListener","method":"onHalfClose","file":"PartialForwardingServerCallListener.java","line":35,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.ForwardingServerCallListener","method":"onHalfClose","file":"ForwardingServerCallListener.java","line":23,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener","method":"onHalfClose","file":"ForwardingServerCallListener.java","line":40,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.Contexts$ContextualizedServerCallListener","method":"onHalfClose","file":"Contexts.java","line":86,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.PartialForwardingServerCallListener","method":"onHalfClose","file":"PartialForwardingServerCallListener.java","line":35,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.ForwardingServerCallListener","method":"onHalfClose","file":"ForwardingServerCallListener.java","line":23,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener","method":"onHalfClose","file":"ForwardingServerCallListener.java","line":40,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl","method":"halfClosed","file":"ServerCallImpl.java","line":283,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed","method":"runInContext","file":"ServerImpl.java","line":710,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.internal.ContextRunnable","method":"run","file":"ContextRunnable.java","line":37,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.internal.SerializeReentrantCallsDirectExecutor","method":"execute","file":"SerializeReentrantCallsDirectExecutor.java","line":49,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener","method":"halfClosed","file":"ServerImpl.java","line":721,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.inprocess.InProcessTransport$InProcessStream$InProcessClientStream","method":"halfClose","file":"InProcessTransport.java","line":634,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.internal.ForwardingClientStream","method":"halfClose","file":"ForwardingClientStream.java","line":67,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.internal.ClientCallImpl","method":"halfClose","file":"ClientCallImpl.java","line":408,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.PartialForwardingClientCall","method":"halfClose","file":"PartialForwardingClientCall.java","line":44,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.ForwardingClientCall","method":"halfClose","file":"ForwardingClientCall.java","line":22,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.ForwardingClientCall$SimpleForwardingClientCall","method":"halfClose","file":"ForwardingClientCall.java","line":44,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.PartialForwardingClientCall","method":"halfClose","file":"PartialForwardingClientCall.java","line":44,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.ForwardingClientCall","method":"halfClose","file":"ForwardingClientCall.java","line":22,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.ForwardingClientCall$SimpleForwardingClientCall","method":"halfClose","file":"ForwardingClientCall.java","line":44,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.PartialForwardingClientCall","method":"halfClose","file":"PartialForwardingClientCall.java","line":44,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.ForwardingClientCall","method":"halfClose","file":"ForwardingClientCall.java","line":22,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.ForwardingClientCall$SimpleForwardingClientCall","method":"halfClose","file":"ForwardingClientCall.java","line":44,"exact":true,"location":"grpc-core-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.stub.ClientCalls","method":"asyncUnaryRequestCall","file":"ClientCalls.java","line":283,"exact":true,"location":"grpc-stub-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.stub.ClientCalls","method":"futureUnaryCall","file":"ClientCalls.java","line":189,"exact":true,"location":"grpc-stub-1.16.1.jar","version":"1.16.1"},{"class":"io.grpc.stub.ClientCalls","method":"blockingUnaryCall","file":"ClientCalls.java","line":127,"exact":true,"location":"grpc-stub-1.16.1.jar","version":"1.16.1"},{"class":"ai.verta.modeldb.HydratedServiceGrpc$HydratedServiceBlockingStub","method":"findHydratedDatasets","file":"HydratedServiceGrpc.java","line":1512,"exact":true,"location":"classes/","version":"?"},{"class":"ai.verta.modeldb.HydratedServiceTest","method":"findHydratedDatasetsTest","file":"HydratedServiceTest.java","line":3844,"exact":true,"location":"test-classes/","version":"?"},{"class":"sun.reflect.NativeMethodAccessorImpl","method":"invoke0","file":"NativeMethodAccessorImpl.java","line":-2,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"sun.reflect.NativeMethodAccessorImpl","method":"invoke","file":"NativeMethodAccessorImpl.java","line":62,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"sun.reflect.DelegatingMethodAccessorImpl","method":"invoke","file":"DelegatingMethodAccessorImpl.java","line":43,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"java.lang.reflect.Method","method":"invoke","file":"Method.java","line":498,"exact":false,"location":"?","version":"1.8.0_242"},{"class":"org.junit.runners.model.FrameworkMethod$1","method":"runReflectiveCall","file":"FrameworkMethod.java","line":50,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.internal.runners.model.ReflectiveCallable","method":"run","file":"ReflectiveCallable.java","line":12,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.runners.model.FrameworkMethod","method":"invokeExplosively","file":"FrameworkMethod.java","line":47,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.internal.runners.statements.InvokeMethod","method":"evaluate","file":"InvokeMethod.java","line":17,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.internal.runners.statements.RunBefores","method":"evaluate","file":"RunBefores.java","line":26,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.internal.runners.statements.RunAfters","method":"evaluate","file":"RunAfters.java","line":27,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"io.grpc.testing.GrpcCleanupRule$1","method":"evaluate","file":"GrpcCleanupRule.java","line":125,"exact":true,"location":"grpc-testing-1.16.1.jar","version":"1.16.1"},{"class":"org.junit.rules.RunRules","method":"evaluate","file":"RunRules.java","line":20,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.runners.ParentRunner","method":"runLeaf","file":"ParentRunner.java","line":325,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.runners.BlockJUnit4ClassRunner","method":"runChild","file":"BlockJUnit4ClassRunner.java","line":78,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.runners.BlockJUnit4ClassRunner","method":"runChild","file":"BlockJUnit4ClassRunner.java","line":57,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.runners.ParentRunner$3","method":"run","file":"ParentRunner.java","line":290,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.runners.ParentRunner$1","method":"schedule","file":"ParentRunner.java","line":71,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.runners.ParentRunner","method":"runChildren","file":"ParentRunner.java","line":288,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.runners.ParentRunner","method":"access$000","file":"ParentRunner.java","line":58,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.runners.ParentRunner$2","method":"evaluate","file":"ParentRunner.java","line":268,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.internal.runners.statements.RunBefores","method":"evaluate","file":"RunBefores.java","line":26,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.internal.runners.statements.RunAfters","method":"evaluate","file":"RunAfters.java","line":27,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.runners.ParentRunner","method":"run","file":"ParentRunner.java","line":363,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"org.junit.runner.JUnitCore","method":"run","file":"JUnitCore.java","line":137,"exact":true,"location":"junit-4.12.jar","version":"4.12"},{"class":"com.intellij.junit4.JUnit4IdeaTestRunner","method":"startRunnerWithArgs","file":"JUnit4IdeaTestRunner.java","line":68,"exact":true,"location":"junit-rt.jar","version":"?"},{"class":"com.intellij.rt.execution.junit.IdeaTestRunner$Repeater","method":"startRunnerWithArgs","file":"IdeaTestRunner.java","line":47,"exact":true,"location":"junit-rt.jar","version":"?"},{"class":"com.intellij.rt.execution.junit.JUnitStarter","method":"prepareStreamsAndStart","file":"JUnitStarter.java","line":242,"exact":true,"location":"junit-rt.jar","version":"?"},{"class":"com.intellij.rt.execution.junit.JUnitStarter","method":"main","file":"JUnitStarter.java","line":70,"exact":true,"location":"junit-rt.jar","version":"?"}]},"endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","instant":{"epochSecond":1582003124,"nanoOfSecond":971000000},"threadId":1,"threadPriority":5}

**Comment by evgeniilezhnin** [comment]
please check other tests

**Comment by ravishetye** [comment]
review comments fixed by @ad-47

**Pull request merged**
