### PR TITLE
fix: make the S3Client reference swap thread-safe

### PR DESCRIPTION
**Pull request by jkwatson-verta**
And add some logging around the periodic refresh job.

## Testing
- [x] Unit test
- [ ] Deployed to dev env
- [ ] Other (explain) 

## Reverting
- [ ] Contains Migration - _Do Not Revert_

### CODE REVIEW

**Comment by jkwatson-verta** [comment]
!rebuild

**Review by conradoverta — APPROVED** [review]

**Comment by jkwatson-verta** [comment]
!rebuild

**Comment by jkwatson-verta** [comment]
closing & re-opening to see if it the build gets properly kicked off.

**Comment by jkwatson-verta** [comment]
> closing & re-opening to see if it the build gets properly kicked off.

the build did not get kicked off. 🤔

**Review by gustavoteixeirah — APPROVED** [review]

**Pull request merged**
