### PR TITLE
Fix update cron query for the MySql

### PR DESCRIPTION
**Pull request by anandjakhaniya**

### CODE REVIEW

**Comment by ravishetye** [comment]
changes make sense to me , can you comment on platform you have tested it on?
- [x] MySQL
- [x] TiDB
- [x] Postgres

**Comment by anandjakhaniya** [comment]
We have a separate query for the Postgres so it works. but changes are generally in a non-postgres query so I have tested it with MySQL & TiDB production version.

**Review by ravishetye — APPROVED** [review]

**Comment by ravishetye** [comment]
Please make similar changes in registry

**Comment by anandjakhaniya** [comment]
Sure.

**Pull request merged**
